Repository Strypper/mauisland, pull requests merged in 2023-02, with the labels that each got.

#68 Add CarouselView
  src/Features/Gallery/Pages/BuiltIn/CarouselView/CarouselItem.cs
  src/Features/Gallery/Pages/BuiltIn/CarouselView/CarouselViewPage.xaml
  src/Features/Gallery/Pages/BuiltIn/CarouselView/CarouselViewPage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/CarouselView/CarouselViewPageViewModel.cs
  src/Features/Gallery/Pages/BuiltIn/CarouselView/ItemDataTemplateSelector.cs
Labels: enhancement

#91 [Bug]: cake build missing property and app bar buttons
  build.cake
  src/Features/Gallery/Pages/Syncfusion/SfBadgeView/SfBadgeViewControlInfo.cs
  src/Features/Gallery/Pages/Syncfusion/SfBadgeView/SfBadgeViewPage.xaml
  src/Features/Gallery/Pages/Syncfusion/SfBadgeView/SfBadgeViewPage.xaml.cs
  src/Features/Gallery/Pages/Syncfusion/SfBadgeView/SfBadgeViewPageViewModel.cs
  src/MauiProgram.cs
Labels: bug

#96 Create add-new-control.yml
  .github/ISSUE_TEMPLATE/add-new-control.yml
Labels: new feature

#97 Implement SfBarCodeGenerator
  src/Features/Gallery/Pages/Syncfusion/SfBarcodeGenerator/SfBarcodeGeneratorControlInfo.cs
  src/Features/Gallery/Pages/Syncfusion/SfBarcodeGenerator/SfBarcodeGeneratorPage.xaml
  src/Features/Gallery/Pages/Syncfusion/SfBarcodeGenerator/SfBarcodeGeneratorPage.xaml.cs
  src/Features/Gallery/Pages/Syncfusion/SfBarcodeGenerator/SfBarcodeGeneratorPageViewModel.cs
  src/MAUIsland.csproj
Labels: new feature

#100 Change Build Action appsettings.Development.json
  src/MAUIsland.csproj
Labels: bug

#52 update collection view
  src/Features/Gallery/Pages/BuiltIn/CollectionView/CollectionViewPage.xaml
  src/Features/Gallery/Pages/BuiltIn/CollectionView/CollectionViewPage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/CollectionView/CollectionViewPageViewModel.cs
Labels: new feature 🚀

#103 85 sfavatarview
  src/Features/Gallery/Pages/Syncfusion/SfAvatarView/SfAvatarViewControlInfo.cs
  src/Features/Gallery/Pages/Syncfusion/SfAvatarView/SfAvatarViewPage.xaml
  src/Features/Gallery/Pages/Syncfusion/SfAvatarView/SfAvatarViewPage.xaml.cs
  src/Features/Gallery/Pages/Syncfusion/SfAvatarView/SfAvatarViewPageViewModel.cs
  src/UI/Views/BreedLabel.xaml
  src/UI/Views/BreedLabel.xaml.cs
Labels: new feature 🚀, syncfusion

#88 82 sfcombobox
  .vscode/launch.json
  src/Features/Gallery/Pages/GalleryPage.xaml.cs
  src/Features/Gallery/Pages/Syncfusion/SfComboBox/SfComboBoxControlInfo.cs
  src/Features/Gallery/Pages/Syncfusion/SfComboBox/SfComboBoxPage.xaml
  src/Features/Gallery/Pages/Syncfusion/SfComboBox/SfComboBoxPage.xaml.cs
  src/Features/Gallery/Pages/Syncfusion/SfComboBox/SfComboBoxPageViewModel.cs
Labels: new feature 🚀, syncfusion

#108 84 sfbadgeview
  src/Features/Gallery/Pages/BuiltIn/DatePicker/Converters/FulldateToDateOnlyConverter.cs
  src/Features/Gallery/Pages/BuiltIn/Stepper/Converters/IntToMrIncreadibleMemeConverter.cs
  src/Features/Gallery/Pages/BuiltIn/Stepper/StepperPage.xaml
  src/Features/Gallery/Pages/Syncfusion/SfBadgeView/SfBadgeViewPage.xaml
  src/Features/Gallery/Pages/Syncfusion/SfBadgeView/SfBadgeViewPageViewModel.cs
  src/Resources/Images/memes/mrincredibleblackwhite.png
  src/Resources/Images/memes/mrincredibleblackwhite1.png
  src/Resources/Images/memes/mrincredibleblackwhite2.png
  src/Resources/Images/memes/mrincredibleblackwhite3.png
  src/Resources/Images/memes/mrincredibleblackwhite4.png
  src/Resources/Images/memes/mrincredibleblackwhite5.png
  src/Resources/Images/memes/mrincrediblesmile.png
  src/Resources/Images/memes/mrincrediblesmile1.png
  src/Resources/Images/memes/mrincrediblesmile2.png
  src/Resources/Images/memes/mrincrediblesmile3.png
  src/Resources/Images/memes/mrincrediblesmile4.png
  src/Resources/Images/memes/mrincrediblesmile5.png
Labels: new feature 🚀, syncfusion, level/easy 🤩
