Repository Strypper/mauisland, pull requests merged in 2023-01, with the labels that each got.

#15 Initial Commit: Entry Page
  MAUIsland/AppRoutes.cs
  MAUIsland/AppShell.xaml.cs
  MAUIsland/Features/Gallery/MAUI/Entry/Pages/EntryPage.xaml
  MAUIsland/Features/Gallery/MAUI/Entry/Pages/EntryPage.xaml.cs
  MAUIsland/Features/Gallery/MAUI/Entry/Pages/EntryPageViewModel.cs
  MAUIsland/Features/Gallery/MAUI/Services/Implementations/MAUIControlsService.cs
  MAUIsland/MAUIsland.csproj
  MAUIsland/MauiProgram.cs
Labels: new feature

#16 Initial Commit: Carousel View
  MAUIsland/AppRoutes.cs
  MAUIsland/AppShell.xaml.cs
  MAUIsland/Features/Gallery/MAUI/CarouselView/Pages/CarouselViewPage.xaml
  MAUIsland/Features/Gallery/MAUI/CarouselView/Pages/CarouselViewPage.xaml.cs
  MAUIsland/Features/Gallery/MAUI/CarouselView/Pages/CarouselViewPageViewModel.cs
  MAUIsland/Features/Gallery/MAUI/Services/Implementations/MAUIControlsService.cs
  MAUIsland/MAUIsland.csproj
  MAUIsland/MauiProgram.cs
Labels: new feature

#18 Initial Commit: Collection View
  MAUIsland/AppRoutes.cs
  MAUIsland/AppShell.xaml.cs
  MAUIsland/Features/Gallery/MAUI/CollectionView/Pages/CollectionViewPage.xaml
  MAUIsland/Features/Gallery/MAUI/CollectionView/Pages/CollectionViewPage.xaml.cs
  MAUIsland/Features/Gallery/MAUI/CollectionView/Pages/CollectionViewPageViewModel.cs
  MAUIsland/Features/Gallery/MAUI/Services/Implementations/MAUIControlsService.cs
  MAUIsland/MAUIsland.csproj
  MAUIsland/MauiProgram.cs
Labels: new feature

#26 Initial Commit: Label Page
  MAUIsland/AppRoutes.cs
  MAUIsland/AppShell.xaml.cs
  MAUIsland/Features/Gallery/MAUI/Label/LabelPage.xaml
  MAUIsland/Features/Gallery/MAUI/Label/LabelPage.xaml.cs
  MAUIsland/Features/Gallery/MAUI/Label/LabelPageViewModel.cs
  MAUIsland/Features/Gallery/MAUI/Services/Implementations/MAUIControlsService.cs
  MAUIsland/MAUIsland.csproj
  MAUIsland/MauiProgram.cs
Labels: new feature

#31 Implement Activity Indicator
  MAUIsland/AppShell.xaml
  MAUIsland/Features/Gallery/MAUI/ActivityIndicator/Pages/ActivityIndicatorPage.xaml
Labels: enhancement

#36 Add CheckBox Control
  MAUIsland/Features/Gallery/MAUI/CheckBox/Pages/CheckBoxPage.xaml
  MAUIsland/Features/Gallery/MAUI/CheckBox/Pages/CheckBoxPageViewModel.cs
Labels: new feature

#41 add Progress Bar
  MAUIsland/Features/Gallery/MAUI/ProgressBar/Pages/ProgressBarPage.xaml
  MAUIsland/Features/Gallery/MAUI/ProgressBar/Pages/ProgressBarPage.xaml.cs
  MAUIsland/Features/Gallery/MAUI/ProgressBar/Pages/ProgressBarPageViewModel.cs
  MAUIsland/Features/Gallery/MAUI/RaditoButton/Pages/RadioButtonPage.xaml
Labels: new feature

#51 Implement Switch
  src/Features/Gallery/Pages/BuiltIn/Switch/SwitchPage.xaml
  src/Features/Gallery/Pages/BuiltIn/Switch/SwitchPage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/Switch/SwitchPageViewModel.cs
Labels: new feature

#50 Implement Indicator View
  src/Features/Gallery/Pages/BuiltIn/IndicatorView/IndicatorViewPage.xaml
  src/Features/Gallery/Pages/BuiltIn/IndicatorView/IndicatorViewPage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/IndicatorView/IndicatorViewPageViewModel.cs
  src/Features/Gallery/Pages/BuiltIn/ProgressBar/ProgressBarPage.xaml
  src/Features/Gallery/Pages/BuiltIn/RaditoButton/RadioButtonPage.xaml
  src/Features/Gallery/Pages/BuiltIn/RaditoButton/RadioButtonPage.xaml.cs
  src/Features/Gallery/Styles/GalleryStyles.xaml
Labels: new feature

#70 Fix HorizontalWrapLayoutManager.Measure
  src/UI/Views/Layouts/HorizontalWrapLayoutManager.cs
Labels: bug

#69 Swipe view
  MAUIsland/Features/Gallery/MAUI/ImageButton/Pages/ImageButtonPage.xaml
  MAUIsland/Features/Gallery/MAUI/RefreshView/Pages/RefreshViewPage.xaml
  MAUIsland/Features/Gallery/MAUI/SearchBar/Pages/SearchBarPage.xaml
  MAUIsland/Features/Gallery/MAUI/SwipeView/Pages/SwipeViewPage.xaml
  src/Features/Gallery/Pages/BuiltIn/SwipeView/SwipeViewPage.xaml
  src/Features/Gallery/Pages/BuiltIn/SwipeView/SwipeViewPage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/SwipeView/SwipeViewPageViewModel.cs
Labels: enhancement

#19 Search Bar Page content added
  MAUIsland/Features/Gallery/MAUI/ImageButton/Pages/ImageButtonPage.xaml
  MAUIsland/Features/Gallery/MAUI/SearchBar/Pages/SearchBarPage.xaml
Labels: documentation, new feature

#71 Frame
  src/Features/Gallery/Pages/BuiltIn/Frame/FramePage.xaml
  src/Features/Gallery/Pages/BuiltIn/Frame/FramePage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/Frame/FramePageViewModel.cs
Labels: enhancement

#72 Implement Searchbar
  src/Features/Gallery/Pages/BuiltIn/SearchBar/SearchBarPage.xaml
  src/Features/Gallery/Pages/BuiltIn/SearchBar/SearchBarPage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/SearchBar/SearchBarPageViewModel.cs
Labels: enhancement

#78 Implement Picker Page
  src/Features/Gallery/Pages/BuiltIn/Picker/PickerPage.xaml
  src/Features/Gallery/Pages/BuiltIn/Picker/PickerPage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/Picker/PickerPageViewModel.cs
Labels: enhancement

#79 Implement Table View
  src/Features/Gallery/Pages/BuiltIn/ImageButton/ImageButtonPageViewModel.cs
  src/Features/Gallery/Pages/BuiltIn/TableView/TableViewPage.xaml
  src/Features/Gallery/Pages/BuiltIn/TableView/TableViewPage.xaml.cs
  src/Features/Gallery/Pages/BuiltIn/TableView/TableViewPageViewModel.cs
Labels: enhancement
